language: bash
git:
  depth: false
os:
  - linux
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
  matrix:
    - JDK="adopt@1.11" PYTHON_VERSION="3.6.3"
before_install:
  - pyenv install $PYTHON_VERSION
  - pyenv local $PYTHON_VERSION
  - python -m venv venv
install:
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - deactivate
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
script:
  - ./gradlew runAll
  - source venv/bin/activate
  - python process.py
  - deactivate
before_deploy:
  - tar -czvf "charts/by-time.tar.gz" $TRAVIS_BUILD_DIR/charts/*/by-time
  - git config --local user.name "Danilo Pianini"
  - git config --local user.email "danilo.pianini@unibo.it"
  - if [[ $(git describe) == *"-"* ]]; then git tag $(git describe) || :; fi
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $PYENV_ROOT
    - $TRAVIS_BUILD_DIR/venv
deploy:
  provider: releases
  api_key:
    secure: NlsJDjIu6rDKhLmpUMlx8cGEf6HLXTX8db5WHD+X7/v38hejVesaVPrftcVpQN9N9Wk1f90fcD+cz3yNBCM3JBelsVnuIKPYQRCUsT8n9FF/S7stSoXwVdDJeXkTjC7K9M/KH/YQjm2fWeH/KHTDNemyfWO+s9B37vVf8y2bSGkeo9a1Lq86Yr9Sq5poeIGk6iWhUdYDUBefX1kJ08k4fidNJPv8v+wH48I8+RtpmiyjQOg4pnqqGOViLj8STFFDGP3fLW+CWxwbEAzWXYBy/97Nc/zk5r7m8iduv/VSceyVl5LdDgp5vKe+Ucnzpg24xWqCV2IIlcX1F7TH57y2Rv/3jHZlWY5qMo1Ad6I3iwrAPXuc9dvbFd2w2AIHPPzr6we5WyTJFOI2TQWdJIhxW5I7ca8GcMjhunmV8rji2P2GPMIiqMieo/zcGNBfEpbTwJAWFzdGO769ircZjk7uTWDGU5+WDxPumJBXwhAhZtvm5AWy++oJbuAgf7/YOt+zPc7vUw2t4gQUmj0M9EEJGnOiVw5gFsgCHkd9QYP9XzwtxTxQ12RBRkE96b+/O9UAcyGT5svrf14Z3Y9AjBQ88XZX+fwbC99SJ2/tDuJUXZHDBsECnTSX7uzqEgqI44dXUBt5bcHvWq/flR1VaaDaaw65bxOvgca1eBwbvTZDvB8=
  skip_cleanup: true
  file_glob: true
  file:
    - "${TRAVIS_BUILD_DIR}/charts/*.tar.gz"
    - "${TRAVIS_BUILD_DIR}/charts/*.pdf"
  on:
    repo: DanySK/Experiment-2019-EAAI-Processes
  #- provider: releases
    #file:
      #- "${TRAVIS_BUILD_DIR}/charts/*.tar.gz"
      #- "${TRAVIS_BUILD_DIR}/charts/*.pdf"
    #edge: true
    #on:
      #repo: DanySK/Experiment-2019-EAAI-Processes
      #tags: false
notifications:
  email:
    recipients:
      - danilo.pianini@unibo.it
      - roby.casadei@unibo.it
      - mirko.viroli@unibo.it
      - giorgio.audrito@unito.it
      - ferruccio.damiani@unito.it
    on_success: never
    on_failure: never
